### PR TITLE
Stage 1 - Welcome Introduction

### PR DESCRIPTION
**Pull request by leggant**
Will add some welcome text to the program that will introduce the user to the program and its purpose.

### CODE REVIEW

**Comment by eallenOP** [comment]
Great to see you're exploring all the features of GitHub! It's actually a pretty good project management tool for software projects.

**Review by Mohammed-alhasan — CHANGES_REQUESTED** [review]
I have added some changes to the code ,please have a look and test it to have a better understanding of the layout @TONIOLEARY @Benedict-ONeill @leggant

**Comment by leggant** [comment]
Looks good to me :)

@chooke1994 I think we should merge\close this pull request in to the stage 1 branch then start a new pull request from the stage 1 branch.

**Review by leggant — COMMENTED** [review]
Looks good to me.  Has everyone tested this code? It works when I tried it.

**Pull request merged**
